###
POST http://localhost:7000/auth/login
Content-Type: application/json

{
    "email":"a@gmail.com",
    "password": "passwosdsfrd"

}

###
POST http://localhost:7000/auth/signup
Content-Type: application/json

{
    "email":"a@gmail.com",
    "firstname":"Allan",
    "lastname" : "namu",
    "password": "password"
}