###
POST http://localhost:7000/auth/login
Content-Type: application/json

{
    "email":"a@gmail.com",
    "password": "passwosdsfrd"
}

###
POST http://localhost:7000/auth/signup
Content-Type: application/json

{
    "email":"a@gmail.com",
    "firstname":"Allan",
    "lastname" : "namu",
    "password": "password"
}

###
POST http://localhost:7000/product
Content-Type: application/json

{
    "id":"randomid",
    "name":"Table",
    "description":"best table in town",
    "imageurl":"randomurl",
    "price":123,
    "discount":10
}

###
GET http://localhost:7000/product